config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/terms_of_service'
  get 'static_pages/privacy_policy'
  root "boards#index"
  resources :users, only: %i[new create]
  resources :boards

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  belongs_to :prefecture

  mount_uploader :board_image, BoardImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  paginates_per 9

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :boards
  has_many :users, through: :board

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :boards, dependent: :destroy
  has_many :visited_prefectures, -> { distinct }, through: :boards, source: :prefecture


  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :user_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login


  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :set_board, only: [:edit, :update, :destroy]
  before_action :set_prefectures, only: [:new, :edit]

  def index
      @boards = Board.all.includes(:user).order(created_at: :desc).page(params[:page]).per(9)
      @visited_prefectures_count = current_user&.visited_prefectures&.count
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
    @prefectures = Prefecture.all
  end

  def create
    @board = current_user.boards.build(board_params)
    @prefectures = Prefecture.all
    if @board.save
      flash[:notice] = I18n.t('flash_message.created', item: Board.model_name.human)
      redirect_to boards_path
    else
      flash.now[:danger] = I18n.t('flash_message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      flash[:notice] = I18n.t('flash_message.updated', item: Board.model_name.human)
      redirect_to root_path
    else
      flash.now[:danger] = I18n.t('flash_message.not_updated', item: Board.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy
    flash[:notice] = I18n.t('flash_message.deleted', item: Board.model_name.human)
    redirect_to boards_path
  end

  private

  def require_login
    unless logged_in?
      flash[:notice] = "ログインしてください"
      redirect_to login_path
    end
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :body, :prefecture_id, :board_image, :board_image_cache)
  end

  def set_prefectures
    @prefectures = Prefecture.all
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _header; end

  def _footer; end

  def _before_login_header; end

  def _flash_message; end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def terms_of_service; end

  def privacy_policy; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'ユーザーが正常に作成されました'
    else
      flash.now[:alert] = 'ユーザー作成に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'Traveary'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <div class="card-images d-flex justify-content-center align-items-center" style="height: 300px;">
        <% if board.board_image.present? %>
          <%= image_tag board.board_image_url, class: 'card-img-top' %>
        <% else %>
          <%= image_tag 'no_image.png', class: 'img-fluid', size: '120x60' %>
        <% end %>
      </div>
      <div class="card-body" style="font-family: Kiwi Maru;">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to board.title, board_path(board) %>
          </h4>
          <div class="ms-auto">
            <% if current_user && current_user.own?(board) %>
              <%= render 'crud_menus', board: board %>
            <% end %>
          </div>
        </div>
        <ul class="list-inline">
          <% if board.prefecture.present? %>
            <%= content_tag :li do %>
              <i class="bi bi-airplane"></i>
              <%= board.prefecture.name %>
            <% end %>
          <% end %>
          <%= content_tag :li do %>
            <i class="bi bi-person"></i>
            <%= board.user.user_name %>
          <% end %>
          <%= content_tag :li do %>
            <i class="bi bi-calendar"></i>
            <%= l board.created_at, format: :long %>
          <% end %>
        </ul>
        <div id="board-body-<%= board.id %>">
          <%= truncate(board.body, length: 25) %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function showMore(boardId) {
      var boardBody = document.getElementById("board-body-" + boardId);
      var moreBtn = document.querySelector("#board-id-" + boardId + " .more-btn");

      if (moreBtn.textContent === "もっと見る") {
          boardBody.innerHTML = "<%= j(board.body) %>"; // 完全なテキストを表示
          moreBtn.textContent = "もっと少なく見る";
      } else {
          boardBody.innerHTML = "<%= j(truncate(board.body, length: 150)) %>"; // 制限されたテキストを表示
          moreBtn.textContent = "もっと見る";
      }
  }
</script>

app/views/boards/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_board_path(board), id: "button-edit-#{board.id}" do %>
      <i class='bi bi-pencil-fill'></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to board_path(board), id: "button-delete-#{board.id}", data: { turbo_method: :delete, turbo_confirm: t('flash_messages.delete_confirm') } do %>
      <i class="bi bi-trash-fill"></i>
    <% end %>
  </li>
</ul>

app/views/boards/_form.html.erb
<%= form_with model: board, local: true do |f| %>
  <div class="form-group mt-4 text-black-50" style="font-family: Kiwi Maru;">
    <%= f.label :prefecture_id, '旅行した都道府県' %>
    <%= f.collection_select :prefecture_id, @prefectures, :id, :name %>
  </div>

  <div class="form-group mt-2 text-black-50">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group mt-2 text-black-50">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>

    <div class="row mb-3">
      <%= f.label :board_image %>
      <%= f.file_field :board_image, multipart: true, class: 'form-control', accept: 'image/*' %>
      <%= f.hidden_field :board_image_cache %>
    </div>
    <div class='col-md-3'>
      <div class="row mb-3">
        <% if @board.board_image.present? %>
          <div class='col-md-6 offset-md-3 text-center'>
            <%= image_tag @board.board_image.url, class: "card-img-top img-fluid", size: '300x200' %>
          </div>
        <% end %>
      </div>
    </div>
    <%= f.submit class: 'btn btn-primary mb-4' %>
<% end %>

app/views/boards/_prefecture.html.erb
<div class="mt-4">
  <div class="shape"></div>
  <div class="content">
    <%= image_tag 'sticker2.png', class: 'img-fluid', width: 130, height: 130 %>
    <div class="info">
      <div class="text-black-50">
        <p>旅行した都道府県の数:</p>
      </div>
      <div class="number">
        <p><%= @visited_prefectures_count %></p>
      </div>
      <div class="text-black-50">
        <p>/47都道府県</p>
      </div>
    </div>
  </div>
</div>

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/destroy.html.erb
<h1>Boards#destroy</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/edit.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', {board: @board} %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class='top-wrapper'>
        <div class='top-inner-text'>
          <h1>Travel + Diary</h1>
        </div>
          <p class='top-inner-comment'>- 旅の思い出をとっておく場所 -</p>
      </div>
    </div>
  </div>

  <!-- 旅行した都道府県の情報 -->
  <% if current_user.present? %>
    <%= render 'prefecture' %>
  <% end %>

  <!-- 掲示板一覧 -->
  <div class="row pt-5">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <p class="text-center"><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @boards, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 text-black-50" style="font-family: Kiwi Maru;">
      <h3><%= t('.title') %></h3>
      <%= render 'form', { board: @board } %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h2 class="d-inline" style='margin-left: 20px'><%= @board.title %></h2>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <% if @board.board_image.present? %>
              <div class='col-md-6 offset-md-3 text-center'>
                <%= image_tag @board.board_image.url, class: "card-img-top img-fluid", size: '300x200' %>
              </div>
            <% end %>
            <% if current_user&.own?(@board) %>
              <div class='d-flex justify-content-end'>
                <%= render 'crud_menus', board: @board %>
              </div>
            <% end %>
            <div class='col-md-6' style='margin: 10px'>
              <p><%= simple_format(@board.body) %></p>
              <ul class="list-inline" style="padding-top: 20px">
                <li class="list-inline-item"><%= "by #{@board.user.user_name}" %></li>
                <li class="list-inline-item"><%= l @board.created_at, format: :long %></li>
              </ul>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <header>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
      <%= render 'shared/flash_message' %>
  </header>
      <%= yield %>
    </main>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="header">
  <nav class="nav d-flex justify-content-center align-items-center pt-4">
    <div class="d-flex align-items-center" style="font-family: Kiwi Maru;">
      <div class='"text-primary'>
        <li><%= link_to 'ログイン', login_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %></li>
      </div>
      <div class='mr-8'>
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo2.png', width: 150, height: 150 %>
          <% end %>
        </div>
      </div>
        <li><%= link_to '新規登録', new_user_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %></li>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
    <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="row mt-4">
<% flash.each do |message_type, message| %>
  <div class="alert <%= message_type == 'notice' ? 'alert-info' : 'alert-danger' %> text-center">
    <%= message %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom' style="background-color: #bbe2f1; display: flex; justify-content: center; align-items: center; height: 50px;">
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12 text-black-50'>
        <div class='copyright'>
          <p style="margin: 0;">Copyright © Traveary</p>
        </div>
      </div>
      <div class='col-sm-6 col-12' style="text-align: right; display: flex; align-items: center; justify-content: flex-end;">
        <div>
          <%= link_to '利用規約', static_pages_terms_of_service_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
        </div>
        <div style="margin-left: 20px;">
          <%= link_to 'プライバシーポリシー', static_pages_privacy_policy_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="nav d-flex justify-content-between align-items-center pt-4 mx-auto">
    <div class="d-flex align-items-center">
      <div class="nav-link">
        <%= link_to '掲示板一覧', root_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
      </div>
      <div class="nav-link">
        <%= link_to '新規投稿', new_board_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
      </div>
    </div>
    <div class="logo">
      <%= link_to root_path do %>
        <%= image_tag 'logo2.png', width: 150, height: 150 %>
      <% end %>
    </div>
    <div class="d-flex align-items-center">
      <div class="nav-link">
        <%= link_to '準備中', '#', class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover' %>
      </div>
      <div>
        <%= link_to 'ログアウト', logout_path, class: 'nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover', data: { turbo_method: :delete } %>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/privacy_policy.html.erb
<div style="border: 2px solid #f7f6fb; padding: 80px; margin: 100px; background-color: #f7f6fb; border-radius: 10px;">
  <div class='text-black-50'>
    <h2>プライバシーポリシー</h2>
      <div class="pt-4">
        <h5>お客様から取得する情報</h5>
          <li>氏名(ニックネームやペンネームも含む)</li>
          <li>メールアドレス</li>
          <li>写真や動画</li>
      </div>

      <div class="pt-2">
        <h5>お客様の情報を利用する目的</h5>
          <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
          <li>お客様の当社サービスの利用履歴を管理するため</li>
          <li>お客様からのお問い合わせに対応するため</li>
          <li>当社の規約や法令に違反する行為に対応するため</li>
        </div>

      <div class="pt-4">
        <h5>第三者提供</h5>
          <p>当社は、個人データについては、お客様の同意なく第三者に提供しません。ただし、以下の例外があります：</p>
            <li>個人データの取扱いを外部に委託する場合</li>
            <li>当社や当社サービスが買収された場合</li>
            <li>事業パートナーと共同利用する場合</li>
            <li>法律によって第三者提供が許されている場合</li>
      </div>

      <div class="pt-4">
        <h5>プライバシーポリシーの変更</h5>
          <p>当社は、必要に応じて、プライバシーポリシーを変更します。変更後のプライバシーポリシーは、効力発生前に適切な方法で周知または通知します。</p>
      </div>

      <div class="pt-4">
        <p>2024年5月31日制定</p>
      </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto" style="font-family: Kiwi Maru;">
      <h2><%= t('.title') %></h2>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
        <%= link_to 'パスワードをお忘れの方はこちら', '#' %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-10 col-lg-8 mx-auto" style="font-family: Kiwi Maru;">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :user_name, class: "form-label" %>
          <%= f.text_field :user_name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control", autocomplete: "username" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control", autocomplete: "new-password" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password" %>
        </div>
        <%= f.submit "登録", class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>